notifications:
  email:
    recipients:
    - albinsharp@gmail.com
    on_success: change
    on_failure: change
language: ruby
rvm:
- 2.3.1
branches:
  only: master
install:
- bundle install
script:
- rackup -P rackup.pid -p 4567 -o 0.0.0.0 &
- rake integration
- kill `cat rackup.pid`
